//! Format-aware silence splicing for paragraph-bounded TTS chunks.
//!
//! See `docs/paragraph-tts-chunking-spec.md` §3.1 / §3.4 and
//! `docs/cartesia-sonic-3-integration-spec.md` §6.4. The orchestrator
//! splices a short silence prefix in front of every chunk's audio so
//! that paragraph and inter-chunk boundaries land with a small,
//! prosodically pleasant pause.
//!
//! ## Two encodings, one trait shape
//!
//! Different TTS providers emit different containers. ElevenLabs and
//! xAI return MP3; Cartesia's WebSocket endpoint emits raw PCM. The
//! splicer is therefore an enum:
//!
//! - [`SilenceSplicer::Mp3`] — pre-computes one silent MPEG-1 Layer
//!   III frame at startup and replicates it `round(ms /
//!   frame_duration_ms)` times. ~26 ms per frame at 44.1 kHz / 128
//!   kbps stereo.
//! - [`SilenceSplicer::Pcm`] — emits `(sample_rate * channels *
//!   bytes_per_sample * ms / 1000)` zero bytes. For 16-bit mono at
//!   44.1 kHz that's 88.2 bytes per millisecond, generated lazily on
//!   demand.
//!
//! Both variants share the same `silence(ms)` and
//! `splice_with_silence(ms, audio)` shape, so the orchestrator
//! doesn't branch on format.
//!
//! ## Why not generate MP3 silence on the fly?
//!
//! Encoding silence at runtime would pull in a libmp3lame-grade
//! encoder dependency for a one-line job. A pre-baked frame is
//! deterministic, byte-exact, and zero-allocation past startup.
//!
//! The canonical frame is checked in at
//! [`SILENCE_FRAME_44100_128_STEREO`]; regenerate it with
//! `tools/generate_silence_frame.py` (uses the `lameenc` PyPI
//! package). All splice/replication logic in this module is fully
//! unit-tested against synthetic frame bytes so it does not depend
//! on the real frame's content.

use super::AudioFormat;

/// Pre-computed silent MPEG-1 Layer III frame, joint stereo,
/// 44.1 kHz, 128 kbps. Exactly 418 bytes covering 1152 PCM samples
/// (~26.122 ms). Generated by encoding 1152 stereo zero-PCM
/// samples through LAME (quality 2) and extracting the first
/// stable post-info-tag frame; see
/// `tools/generate_silence_frame.py` for the recipe.
pub const SILENCE_FRAME_44100_128_STEREO: &[u8] =
    include_bytes!("silence_frame_44100_128_stereo.mp3");

/// Decoded PCM duration of [`SILENCE_FRAME_44100_128_STEREO`] in
/// milliseconds. `1152 / 44100 * 1000 ≈ 26.122` ms; we round to
/// the nearest whole millisecond since the splicer's frame-count
/// arithmetic is integer-only.
pub const SILENCE_FRAME_44100_128_STEREO_DURATION_MS: u32 = 26;

/// Splices silence in front of audio chunks. Format-aware so the
/// orchestrator can splice MP3 silence into MP3 streams and PCM
/// silence into PCM streams without branching at the call site.
///
/// Cheap to clone — the MP3 variant carries a `&'static` slice plus
/// two integers; the PCM variant carries three integers.
#[derive(Debug, Clone)]
pub enum SilenceSplicer {
    /// MP3 splicer. Replicates a pre-computed silent MP3 frame to
    /// approximate the requested duration. Achievable precision is
    /// one frame (~±13 ms either side); the spec accepts ±15 ms.
    Mp3 {
        /// One MP3 frame whose decoded PCM is all-zero samples.
        frame: &'static [u8],
        /// Decoded PCM duration of `frame` in milliseconds.
        frame_duration_ms: u32,
    },
    /// Raw-PCM splicer. Produces exactly `ms` of zero bytes at the
    /// given format. Sample-accurate (no frame quantization).
    Pcm {
        /// Samples per second per channel.
        sample_rate: u32,
        /// Channel count (1 for Cartesia mono, 2 for stereo).
        channels: u16,
        /// Bytes per sample per channel (2 for `pcm_s16le`).
        bytes_per_sample: u16,
    },
}

impl SilenceSplicer {
    /// Build the canonical 44.1 kHz / 128 kbps stereo MP3 splicer.
    /// Used by callers wired to MP3 providers (ElevenLabs, xAI).
    pub fn default_44100_128_stereo() -> Self {
        Self::Mp3 {
            frame: SILENCE_FRAME_44100_128_STEREO,
            frame_duration_ms: SILENCE_FRAME_44100_128_STEREO_DURATION_MS,
        }
    }

    /// Build a PCM splicer that emits zero bytes shaped to the
    /// given format. Used by Cartesia and any other PCM provider.
    pub fn pcm(sample_rate: u32, channels: u16, bytes_per_sample: u16) -> Self {
        debug_assert!(sample_rate > 0, "sample_rate must be > 0");
        debug_assert!(channels > 0, "channels must be > 0");
        debug_assert!(bytes_per_sample > 0, "bytes_per_sample must be > 0");
        Self::Pcm {
            sample_rate,
            channels,
            bytes_per_sample,
        }
    }

    /// Build a splicer matching a provider's declared
    /// [`AudioFormat`]. The single entry point the orchestrator
    /// uses; eliminates per-provider construction branches at the
    /// startup wiring sites.
    pub fn for_format(fmt: AudioFormat) -> Self {
        match fmt {
            AudioFormat::Mp3_44100_128 => Self::default_44100_128_stereo(),
            AudioFormat::Pcm_S16LE_44100_Mono => {
                Self::pcm(fmt.sample_rate(), fmt.channels(), fmt.bytes_per_sample())
            }
        }
    }

    /// Smallest unit of silence the splicer can produce, expressed in
    /// milliseconds. For MP3 this is the underlying frame's decoded
    /// duration (~26 ms). For PCM, silence is sample-accurate, so we
    /// report `1` ms. Exposed so callers can reason about achievable
    /// precision.
    pub fn frame_duration_ms(&self) -> u32 {
        match self {
            Self::Mp3 {
                frame_duration_ms, ..
            } => *frame_duration_ms,
            Self::Pcm { .. } => 1,
        }
    }

    /// Produce approximately `duration_ms` of silence as raw
    /// container bytes. `duration_ms == 0` returns an empty `Vec`.
    pub fn silence(&self, duration_ms: u32) -> Vec<u8> {
        if duration_ms == 0 {
            return Vec::new();
        }
        match self {
            Self::Mp3 {
                frame,
                frame_duration_ms,
            } => {
                let frames = mp3_frame_count_for(*frame_duration_ms, duration_ms);
                let mut out = Vec::with_capacity(frame.len() * frames as usize);
                for _ in 0..frames {
                    out.extend_from_slice(frame);
                }
                out
            }
            Self::Pcm {
                sample_rate,
                channels,
                bytes_per_sample,
            } => {
                let len = pcm_byte_count(*sample_rate, *channels, *bytes_per_sample, duration_ms);
                vec![0u8; len]
            }
        }
    }

    /// Prepend `silence_ms` of silence to `audio` and return the
    /// concatenated bytes.
    pub fn splice_with_silence(&self, silence_ms: u32, audio: &[u8]) -> Vec<u8> {
        if silence_ms == 0 {
            return audio.to_vec();
        }
        let silence = self.silence(silence_ms);
        let mut out = Vec::with_capacity(silence.len() + audio.len());
        out.extend_from_slice(&silence);
        out.extend_from_slice(audio);
        out
    }
}

/// Round `duration_ms` to the nearest whole number of MP3 frames,
/// with a floor of 1 frame for any non-zero request. The floor
/// matters for short requests like `first_chunk_silence_ms = 100`
/// when the frame duration is 26 ms: requesting 100 ms must produce
/// *some* silence (4 frames ≈ 104 ms), not zero.
fn mp3_frame_count_for(frame_duration_ms: u32, duration_ms: u32) -> u32 {
    let half = frame_duration_ms / 2;
    let n = (duration_ms + half) / frame_duration_ms;
    n.max(1)
}

/// Compute the byte count for `duration_ms` of silence at the given
/// PCM format. Uses 64-bit arithmetic so we don't overflow on long
/// silences (e.g. 60 s of 44.1 kHz stereo 16-bit ≈ 10.5 MB). Returns
/// a multiple of `frame_size = channels * bytes_per_sample` so the
/// browser sink doesn't see a torn final frame.
fn pcm_byte_count(
    sample_rate: u32,
    channels: u16,
    bytes_per_sample: u16,
    duration_ms: u32,
) -> usize {
    let frame_size = channels as u64 * bytes_per_sample as u64;
    let total_samples = (sample_rate as u64) * (duration_ms as u64) / 1000;
    let aligned_samples = total_samples; // sample_rate ≥ 1000 and ms ≥ 0 → fine
    (aligned_samples * frame_size) as usize
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 8-byte synthetic "frame" worth 26 ms of silence. The splicer
    /// doesn't care what the bytes mean — it only replicates them.
    /// Real wiring uses a 417-byte 44.1 kHz/128 kbps stereo MP3
    /// silence frame loaded from `SILENCE_FRAME_44100_128_STEREO`.
    const FAKE_FRAME: &[u8] = b"FRAMExxx";
    const FAKE_FRAME_MS: u32 = 26;

    fn mp3_splicer() -> SilenceSplicer {
        SilenceSplicer::Mp3 {
            frame: FAKE_FRAME,
            frame_duration_ms: FAKE_FRAME_MS,
        }
    }

    // ── MP3 variant ────────────────────────────────────────────────

    #[test]
    fn mp3_silence_zero_returns_empty() {
        let s = mp3_splicer();
        assert!(s.silence(0).is_empty());
    }

    #[test]
    fn mp3_silence_short_request_floors_at_one_frame() {
        let out = mp3_splicer().silence(5);
        assert_eq!(out.len(), FAKE_FRAME.len());
        assert_eq!(&out, FAKE_FRAME);
    }

    #[test]
    fn mp3_silence_rounds_to_nearest_frame() {
        let s = mp3_splicer();
        // 100 ms / 26 ms = 3.846 → rounds up to 4 frames (~104 ms).
        let out = s.silence(100);
        assert_eq!(out.len(), 4 * FAKE_FRAME.len());
        // 39 ms / 26 ms = 1.5 → half-up rounds to 2 frames.
        let out = s.silence(39);
        assert_eq!(out.len(), 2 * FAKE_FRAME.len());
        // 12 ms / 26 ms = 0.46 → rounds down to 0, but floor lifts to 1.
        let out = s.silence(12);
        assert_eq!(out.len(), FAKE_FRAME.len());
    }

    #[test]
    fn mp3_silence_long_request_concatenates_correctly() {
        let s = mp3_splicer();
        // 500 ms / 26 ms = 19.23 → 19 frames.
        let out = s.silence(500);
        assert_eq!(out.len(), 19 * FAKE_FRAME.len());
        for chunk in out.chunks(FAKE_FRAME.len()) {
            assert_eq!(chunk, FAKE_FRAME);
        }
    }

    #[test]
    fn mp3_splice_with_zero_silence_returns_audio_only() {
        let audio = b"AUDIO_BYTES";
        let out = mp3_splicer().splice_with_silence(0, audio);
        assert_eq!(out, audio);
    }

    #[test]
    fn mp3_splice_prepends_silence_then_audio() {
        let audio = b"AUDIO_BYTES";
        let out = mp3_splicer().splice_with_silence(500, audio);
        let header_len = 19 * FAKE_FRAME.len();
        assert_eq!(out.len(), header_len + audio.len());
        assert_eq!(&out[header_len..], audio);
        assert_eq!(&out[..header_len], mp3_splicer().silence(500).as_slice());
    }

    #[test]
    fn mp3_frame_duration_is_exposed_for_caller_diagnostics() {
        assert_eq!(mp3_splicer().frame_duration_ms(), FAKE_FRAME_MS);
    }

    /// The checked-in silence frame must be a valid MPEG-1 Layer
    /// III, 44.1 kHz, 128 kbps, stereo (any channel mode) frame
    /// covering 1152 PCM samples.
    #[test]
    fn embedded_silence_frame_has_expected_mpeg_header() {
        let frame = SILENCE_FRAME_44100_128_STEREO;
        assert_eq!(frame.len(), 418, "expected one padded MP3 frame");
        assert_eq!(frame[0], 0xFF, "missing MPEG sync byte 1");
        assert_eq!(
            frame[1] & 0xFE,
            0xFA,
            "byte 2 must be 0xFA or 0xFB (MPEG1 LayerIII)"
        );
        assert_eq!(frame[2] >> 4, 0b1001, "bitrate must be 128 kbps");
        assert_eq!((frame[2] >> 2) & 0b11, 0b00, "sample rate must be 44.1 kHz");
        assert_eq!(
            (frame[2] >> 1) & 0b1,
            1,
            "padding bit must be set (418-byte frame)"
        );
        assert_eq!(SILENCE_FRAME_44100_128_STEREO_DURATION_MS, 26);
    }

    #[test]
    fn default_constructor_uses_embedded_frame() {
        let s = SilenceSplicer::default_44100_128_stereo();
        assert_eq!(s.frame_duration_ms(), 26);
        let one = s.silence(s.frame_duration_ms());
        assert_eq!(one.as_slice(), SILENCE_FRAME_44100_128_STEREO);
    }

    // ── PCM variant ────────────────────────────────────────────────

    fn pcm_mono() -> SilenceSplicer {
        SilenceSplicer::pcm(44_100, 1, 2)
    }

    #[test]
    fn pcm_silence_zero_returns_empty() {
        assert!(pcm_mono().silence(0).is_empty());
    }

    #[test]
    fn pcm_silence_one_ms_is_44_samples_at_44100_mono() {
        // 44_100 samples/s / 1000 ms = 44 samples/ms → 88 bytes for
        // 16-bit mono.
        let out = pcm_mono().silence(1);
        assert_eq!(out.len(), 44 * 2);
        assert!(out.iter().all(|b| *b == 0));
    }

    #[test]
    fn pcm_silence_500ms_at_44100_mono_is_44_100_bytes() {
        // 22 050 samples * 2 bytes/sample = 44 100 bytes.
        let out = pcm_mono().silence(500);
        assert_eq!(out.len(), 44_100);
        assert!(out.iter().all(|b| *b == 0));
    }

    #[test]
    fn pcm_silence_stereo_doubles_byte_count() {
        let s = SilenceSplicer::pcm(44_100, 2, 2);
        let out = s.silence(1000);
        // 44 100 samples * 2 channels * 2 bytes = 176 400 bytes.
        assert_eq!(out.len(), 176_400);
    }

    #[test]
    fn pcm_silence_byte_count_aligns_to_frame_boundary() {
        // 1 ms at 48 kHz stereo 16-bit = 48 samples * 4 bytes/frame
        // = 192 bytes — a multiple of frame_size (4).
        let s = SilenceSplicer::pcm(48_000, 2, 2);
        let out = s.silence(1);
        assert_eq!(out.len() % 4, 0);
    }

    #[test]
    fn pcm_splice_prepends_zero_bytes_then_audio() {
        let audio = b"AUDIO_BYTES";
        let out = pcm_mono().splice_with_silence(10, audio);
        // 10 ms = 441 samples * 2 bytes = 882 bytes of silence.
        assert_eq!(out.len(), 882 + audio.len());
        assert!(out[..882].iter().all(|b| *b == 0));
        assert_eq!(&out[882..], audio);
    }

    #[test]
    fn pcm_frame_duration_is_one_ms() {
        assert_eq!(pcm_mono().frame_duration_ms(), 1);
    }

    // ── for_format ─────────────────────────────────────────────────

    #[test]
    fn for_format_mp3_yields_mp3_variant() {
        let s = SilenceSplicer::for_format(AudioFormat::Mp3_44100_128);
        assert!(matches!(s, SilenceSplicer::Mp3 { .. }));
    }

    #[test]
    fn for_format_pcm_yields_pcm_variant_with_correct_shape() {
        let s = SilenceSplicer::for_format(AudioFormat::Pcm_S16LE_44100_Mono);
        match s {
            SilenceSplicer::Pcm {
                sample_rate,
                channels,
                bytes_per_sample,
            } => {
                assert_eq!(sample_rate, 44_100);
                assert_eq!(channels, 1);
                assert_eq!(bytes_per_sample, 2);
            }
            other => panic!("expected Pcm, got {other:?}"),
        }
    }
}
